/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#857461",
        "surface-variant": "#e4e2de",
        "error-container": "#ffdad6",
        "background": "#fbf9f5",
        "secondary-fixed-dim": "#c6c6ce",
        "on-background": "#1b1c1a",
        "on-secondary-fixed": "#1a1b21",
        "secondary-fixed": "#e3e1ea",
        "primary-fixed": "#ffddb5",
        "primary": "#845400",
        "primary-fixed-dim": "#ffb958",
        "surface-container-low": "#f5f3ef",
        "tertiary-fixed-dim": "#cec5b8",
        "secondary": "#5d5e65",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#4c463c",
        "on-tertiary-fixed": "#1f1b12",
        "outline-variant": "#d8c3ad",
        "on-tertiary-container": "#484238",
        "on-primary": "#ffffff",
        "surface-dim": "#dbdad6",
        "surface-bright": "#fbf9f5",
        "inverse-primary": "#ffb958",
        "on-secondary-container": "#63646b",
        "primary-container": "#f19e01",
        "surface-tint": "#845400",
        "surface-container-highest": "#e4e2de",
        "on-primary-fixed-variant": "#643f00",
        "on-secondary-fixed-variant": "#46464d",
        "on-secondary": "#ffffff",
        "tertiary-container": "#b7afa2",
        "surface-container-high": "#eae8e4",
        "on-tertiary": "#ffffff",
        "tertiary": "#645e52",
        "inverse-on-surface": "#f2f0ed",
        "surface-container": "#efeeea",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1c1a",
        "on-error-container": "#93000a",
        "surface": "#fbf9f5",
        "on-primary-fixed": "#2a1800",
        "error": "#ba1a1a",
        "on-primary-container": "#5e3b00",
        "inverse-surface": "#30312e",
        "on-surface-variant": "#524433",
        "tertiary-fixed": "#ebe1d3",
        "secondary-container": "#e3e1ea",
        "emerald": {
          DEFAULT: "#10b981",
          dim: "rgba(16, 185, 129, 0.12)",
        },
        "coral": "#ff6b6b",
      },
      fontFamily: {
        display: ['Roboto', 'sans-serif'],
        headline: ['Roboto', 'sans-serif'],
        body: ['Roboto', 'sans-serif'],
        sans: ['Roboto', 'sans-serif'],
        code: ['JetBrains Mono', 'monospace'],
        mono: ['JetBrains Mono', 'monospace'],
        label: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.03em', fontWeight: '500' }],
        'code': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        'gutter': '24px',
        'base': '8px',
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
      },
      letterSpacing: {
        tightest: '-0.04em',
        tighter: '-0.03em',
      },
      boxShadow: {
        custom: '0 4px 20px rgba(31, 32, 38, 0.04)',
        'custom-hover': '0 12px 30px rgba(31, 32, 38, 0.08)',
      },
    },
  },
  plugins: [],
}
